version: '3'

services:
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: sandbox-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    depends_on:
      - mysql
    links:
      - mysql

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: sandbox-mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sandbox
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox
